config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :matches, only: [:index, :show, :new, :create] do
    resources :messages, only: [:create]
    member do
      patch :update_results
      get "ready", to: "matches#match_ready"
    end
    resources :user_matches, only: [:create]
  end

  get "my_matches", to: "matches#mymatches"
  get "my_profile", to: "pages#myprofile"
  get "cancelmymatch/:id", to: "user_matches#cancel_match"
  get "acceptusermatch/:id", to: "user_matches#acceptuser"
  get "rejectusermatch/:id", to: "user_matches#rejectuser"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>


<% if success %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= success %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>


<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar" style="padding: 0px 70px;">
  <%= link_to root_path do%>
    <%= image_tag "play-logo.png", class:"logo"%>
  <% end %>

  <div class="d-flex align-items-center">
    <%= link_to "Make your own match!", new_match_path, class:"join-btn mx-2", style:"text-decoration:none" %>

    <% if user_signed_in? %>
      <div class="dropdown" style="width:auto">
        <% if current_user.photo.attached?  %>
          <%= cl_image_tag current_user.photo.key , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }, style: "width: 55px; height: 55px;" %>
        <% else %>
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }, style: "width: 55px; height: 55px;" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-start" style="top: 100%; left: 0; transform: translate(-125px, 0);" aria-labelledby="navbarDropdown">
          <li><%= link_to "Profile", my_profile_path, class: "dropdown-item" %></li>
          <li><%= link_to "My Matches", my_matches_path, class: "dropdown-item" %></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link login-hover"%>
    <% end %>
  </div>
</div>