config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :matches, only: [:index, :show, :new, :create] do
    resources :messages, only: [:create]
    member do
      patch :update_results
      get "ready", to: "matches#match_ready"
    end
    resources :user_matches, only: [:create]
  end

  get "my_matches", to: "matches#mymatches"
  get "my_profile", to: "pages#myprofile"
  get "cancelmymatch/:id", to: "user_matches#cancel_match"
  get "acceptusermatch/:id", to: "user_matches#acceptuser"
  get "rejectusermatch/:id", to: "user_matches#rejectuser"
end

app/views/pages/home.html.erb
<div style="">
  <div class="banner">
  <div class="search-ttl">
    <h1>PlayPal</h1>
    <p>Connecting players, one game at a time!</p>
    <div class="search-container">
      <form class="search-form" action="/matches">
        <div class="dropdown-row">
          <div class="dropdown">
            <select name="sport" id="sport">
              <option value="" disabled selected hidden>Sport</option>
              <!-- Add your sports options here -->
              <%@sports.each do |sport| %>
                <option value="<%=sport.name%>"><%= sport.name.capitalize%></option>
              <% end %>

            </select>
            <i class="fa-solid fa-caret-down"></i>
          </div>
          <div class="dropdown">
            <select name="level" id="level">
              <option value="" disabled selected hidden>Level</option>
              <!-- Add your match options here -->
              <option value="Beginner">Beginner</option>
              <option value="Intermediate">Intermediate</option>
              <option value="Advanced">Advanced</option>
            </select>
            <i class="fa-solid fa-caret-down"></i>
          </div>
        </div>
        <div class="dropdown-row">
          <div class="dropdown">
            <input placeholder="Date" class="w-100" style="appearance: none;border-radius:20px;padding: 10px 40px 10px 20px;border: 1px solid #ccc;background-color: #fff;font-size: 16px;" name="date" id="date" data-controller="datepicker">
            <i class="fa-solid fa-caret-down"></i>
          </div>
          <div class="dropdown">
            <select name="time" id="time">
              <option value="" disabled selected hidden>Time</option>
          <!-- Add your time options here -->
              <option value="08:00">08:00</option>
              <option value="08:30">08:30</option>
              <option value="09:00">09:00</option>
              <option value="09:30">09:30</option>
              <option value="10:00">10:00</option>
              <option value="10:30">10:30</option>
              <option value="11:00">11:00</option>
              <option value="11:30">11:30</option>
              <option value="12:00">12:00</option>
              <option value="12:30">12:30</option>
              <option value="13:00">13:00</option>
              <option value="13:30">13:30</option>
              <option value="14:00">14:00</option>
              <option value="14:30">14:30</option>
              <option value="15:00">15:00</option>
              <option value="15:30">15:30</option>
              <option value="16:00">16:00</option>
              <option value="16:30">16:30</option>
              <option value="17:00">17:00</option>
              <option value="17:30">17:30</option>
              <option value="18:00">18:00</option>
              <option value="18:30">18:30</option>
              <option value="19:00">19:00</option>
              <option value="19:30">19:30</option>
              <option value="20:00">20:00</option>
              <option value="20:30">20:30</option>
              <option value="21:00">21:00</option>
              <option value="21:30">21:30</option>
              <option value="22:00">22:00</option>
            </select>
            <i class="fa-solid fa-caret-down"></i>
          </div>
        </div>
        <button type="submit" class="join-match-btn">Search match</button>
      </form>
    </div>
  </div>
</div>

<div class="categories">
  <div class="cat-title">
    <h1>Categories</h1>
    <p>You don't need to restrict yourself to just one sport, play in whatever categories you want. You can play at competitive levels, but you can also play at lower competition levels and try sports you've never played before. There's a place for everyone, on PlayPal.</p>
  </div>
  <div class="cat-items">
    <div class="sport-av first-cat">
      <h2 id="first-cat">Padel</h2>
      <i class="fa-solid fa-arrow-right fa-rotate-by fa-2xl " style="--fa-rotate-angle: -30deg; color:#00867A;""></i>
    </div >
    <div class="sport-av">
      <h2>Football</h2>
      <i class="fa-solid fa-arrow-right fa-rotate-by fa-2xl " style="--fa-rotate-angle: -30deg; color:#5CBC30;""></i>
    </div>
    <div class="sport-av">
      <h2>Basketball</h2>
      <i class="fa-solid fa-arrow-right fa-rotate-by fa-2xl" style="--fa-rotate-angle: -30deg; color:#9ADD00;""></i>
    </div>
    <div class="sport-av-i">
      <h2>& More!</h2>
      <%= link_to  matches_path do %>
      <i class="fa-solid fa-circle-info fa-2xl mt-3"></i>
      <% end %>
    </div>
  </div>
</div>

<div class="section-3 border p-5" style="height:790px">
  <div class="d-flex flex-column align-items-center justify-content-center">
    <h2 class="whats-happening text-center" style="width:31.25rem">What's happening this week</h2>
    <p class="whats-happening-para text-center text-style" style="width:32rem">Sports can be very competitive sometimes, so we also organize some chilled events for players to get to know each other in a more relaxed environment.</p>
  </div>
  <div class="d-flex justify-content-center">
    <div style="width:28.375rem;height:28.875rem" class="mx-4 mt-2 mb-4 justify-content-center d-flex flex-column align-items-center bg-white rounded-5">
      <%= image_tag "landing-pic.jpg", class:"landing-pic-size"%>
      <div class="text-center section-3-card-size">
        <h3 style="font-size: 24px; margin-top: 10px;">Padel Tournament</h3>
        <p class="text-style">Join our Padel Tournament, meet players of different levels and find team mates to play with or just have fun!</p>
      </div>
    </div>
    <div style="width:28.375rem;height:28.875rem" class="justify-content-center mt-2 mb-4 d-flex flex-column align-items-center bg-white rounded-5">
      <%= image_tag "landing-pic2.jpg", class:"landing-pic-size"%>
      <div class="text-center section-3-card-size">
        <h3 style="font-size: 24px; margin-top: 10px;">Meet & Greet</h3>
        <p class="text-style">Meet players from every sport for drinks. It's a nice opportunity to learn more about us and make your future sports experiences even more enjoyable.</p>
      </div>
    </div>
  </div>
</div>


  <div class="section-3 border p-5" style="height:790px">
    <div class="d-flex flex-column align-items-center justify-content-center">
      <h2 class="whats-happening text-center" style="width:31.25rem ;margin-bottom:24px">Why playpal will work for you</h2>
      <p class="whats-happening-para text-center text-style" style="width:32rem">We make it possible for you to play sports anytime, anywhere and always have team players that share the same passion.</p>
    </div>

  <div class="why-steps" style="width:940px">
    <div class="step " style="width:292px; height:346px">
      <%= image_tag "Playicon3.png" %>
      <h2 class="text-center" style="margin-bottom: 12px;">Practice Team sports anywhere</h2>
      <p class="text-center text-style">Just tell us where and when and PlayPal will find the nearest matches.</p>
    </div>
    <div class="step" style="width:292px; height:346px">
      <%= image_tag "Playicon1.png" %>
      <h2 class="text-center" style="margin-bottom: 12px;">Connect and meet with new people</h2>
      <p class="text-center text-style">You can rely on PlayPal to find team players for you to share amazing experiences with.</p>
    </div>
    <div class="step" style="width:292px; height:346px">
      <%= image_tag "Playicon2.png" %>
      <h2 class="text-center" style="margin-bottom: 12px;">Easy to know new places, new cities</h2>
      <p class="text-center text-style">You may choose to play in any city you like and get to know new places with tips from your local teammates.</p>

    </div>
  </div>
   </div>

<div style="height:30.25rem" class="d-flex justify-content-center align-items-center border bg-white">

  <div class="mx-3" style="display:inline-block">
    <h2 style="font-size:3rem">FAQs</h2>
    <p class="text-style" style="width:28.375rem;margin:2rem 0">Search our FAQ to learn more about PlayPal and how to get the most out of what we have to offer. If you still have questions, contact us.</p>
    <button class="border border-dark bg-white" style="height:3.3rem;width:11rem;font-size:1.125rem; border-radius: 57px;">Know more</button>
  </div>

  <div class="mx-3" style="display:inline-block;">
    <div style="width:28.375rem" class="border-top border-bottom d-flex justify-content-between align-items-center p-3">
      <p class="my-2">How can I join a match?</p>
      <i class="fa-solid fa-plus highlight-text fs-5"></i>
    </div>
     <div style="width:28.375rem" class="border-top border-bottom d-flex justify-content-between align-items-center p-3">
      <p class="my-2">Do I have to pay to play?</p>
      <i class="fa-solid fa-plus highlight-text fs-5"></i>
    </div>
     <div style="width:28.375rem" class="border-top border-bottom d-flex justify-content-between align-items-center p-3">
      <p class="my-2">How can I withdraw from a game if I cannot attend?</p>
      <i class="fa-solid fa-plus highlight-text fs-5"></i>
    </div>
     <div style="width:28.375rem" class="border-top border-bottom d-flex justify-content-between align-items-center p-3">
      <p class="my-2">Are there rules of conduct for participating?</p>
      <i class="fa-solid fa-plus highlight-text fs-5"></i>
    </div>

  </div>

</div>


<div class="d-flex justify-content-center align-items-center" style="background-image:url(<%=image_path "Section-5.png"%>);background-size:cover;height:35.6875rem">
  <div class="d-flex justify-content-evenly align-items-start">
    <div class="mx-3 container" style="width:30rem">
      <h2 class="text-white" style="font-size:3rem;">Join the team!</h2>
    </div>
    <div class="mx-3 d-flex justify-items-end flex-column" style="">
      <p style="width:30rem" class="text-white">PlayPal is more than just playing sports. We want you to have unique, fun experiences, more or less competitive depending on what you expect to find. We want to unite people around healthy practices</p>
       <%= link_to "Search match", matches_path, class:"join-btn", style:"text-decoration:none;border:none;width:200px"%>
    </div>
  </div>
</div>

<div class="container px-5 d-flex justify-content-between align-items-center" style="height:26.3125rem">
  <div class="" style="width:28.375rem">
    <%= image_tag "play-logo.png", style: "margin-bottom: 24px;" %>
    <p class="text-style">a masterpiece developed by PlayPal, Inc.&reg;</p>
  </div>
  <div style="width:6.9375rem"class="">
    <ul style="list-style-type: none;padding-left:0;font-size:18px;font-weight:bold">
      <li>About us</li>
      <li>Testimonials</li>
      <li>Contacts</li>
    </ul>
  </div>
  <div class="d-flex flex-column">
        <button onclick="location.href='/users/sign_up'" class="join-btn mb-4" style="border: none; width: 11rem; height: 3.3125rem; border-radius: 57px;">Signup!</button>
        <button onclick="location.href='matches';" class="border border-dark bg-white" style="height: 3.3125rem; width: 11rem; font-size: 1.125rem; border-radius: 57px;">Search match!</button>
  </div>
</div>

</div>

app/views/pages/myprofile.html.erb
<div class="show-profile">
  <div class="prof-info align-items-center">
    <%= @user.photo.attached? ? cl_image_tag(@user.photo.key, class:"avatar") : image_tag( asset_path "user.png", class:"avatar") %>
    <div>
      <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      <p>Plays in Madrid, Spain</p>
    </div>
  </div>
  <div class="prof-stats">
    <div class="d-flex flex-column text-center">
      <p><%= @total_matches.to_i %></p>
      <h2>Matches</h2>
    </div>
    <div class="vl"></div>
    <div class="d-flex flex-column text-center">
      <p><%= @total_wins.to_i %></p>
      <h2>Wins</h2>
    </div>
    <div class="vl"></div>
    <div class="d-flex flex-column text-center">
      <p><%= @total_losses.to_i %></p>
      <h2>Losses</h2>
    </div>
  </div>
  <div class="prof-rectangles">
    <div class="rectangle main">
      <div class="star">★</div>
      <div class="rating"><%= @user.rating %></div>
      <div class="label">Level Rating *</div>
    </div>
    <div class="rectangle secondary">
      <div class="star">★</div>
      <% win_percent = @total_matches.zero? ?  "0" : ((( @total_wins / @total_matches ) * 100.0 ).ceil) %>
      <div class="percentage"><%= win_percent %>%</div>
      <div class="text-profile">Of matches won</div>
        </div>
    <div class="rectangle secondary">
      <div class="star">★</div>
      <div class="percentage"><%= ((current_user.rating / 5.0 ) * 100.0).ceil%>%</div>
      <div class="text-profile">Level Reliability</div>
    </div>
  </div>
  <div class="match-history">
    <h1>Match History</h1>
    <div class="match-cards overflow-scroll d-flex w-100">
        <% @user_matches.each do |usermatch| %>
        <% match = usermatch.match %>
          <% if match.ready %>
            <%= link_to match_path(usermatch.match),  style:"text-decoration:none;color:black" do %>
              <div class="match-card">
                  <div class="dateRes">Thur 26</div>
                    <div class="teams">
                        <h2>A</h2>
                        <div class="teamA" style="position:relative">

                            <% ((match.sport.number_of_players / 2) - (match.UserMatches.where(team: "teamA").count)).times do %>
                              <%= image_tag "profile-user.png", class:"avatar" %>
                            <% end %>
                            <% match.UserMatches.where(team: "teamA").each do |usermatch|%>
                              <% if  usermatch.user.photo.attached? %>
                                <%= cl_image_tag usermatch.user.photo.key, class:"avatar"%>
                              <% else %>
                                 <% if usermatch.user == current_user %>
                                  <%= image_tag "user.png", class:"avatar", alt:"My Spot" %>
                                <% else %>
                                  <%= image_tag "profile-user.png", class:"avatar", alt:"accepted player"%>
                                <% end %>
                              <% end %>

                            <% end %>
                        </div>
                        <hr class="team-divider">
                        <h2>B</h2>
                        <div class="teamB">

                            <% ((match.sport.number_of_players / 2) - (match.UserMatches.where(team: "teamB").count)).times do %>
                               <%= image_tag "profile-user.png", class:"avatar" %>
                            <% end %>
                            <% match.UserMatches.where(team: "teamB").each do |usermatch|%>
                              <% if  usermatch.user.photo.attached? %>
                                <%= cl_image_tag usermatch.user.photo.key, class:"avatar"%>
                              <% else %>
                                  <% if usermatch.user == current_user %>
                                    <%= image_tag "user.png", class:"avatar", alt:"My Spot" %>
                                  <% else %>
                                    <%= image_tag "profile-user.png", class:"avatar", alt:"accepted player"%>
                                  <% end %>
                              <% end %>

                            <% end %>
                        </div>
                    </div>
                    <div class="score h-100">
                      <div class="result">
                          <h2>Results</h2>
                          <div><%= match.team_a_score%></div>
                          <hr>
                          <div><%= match.team_b_score %></div>
                      </div>
                  </div>
              </div>
            <% end %>
            <% end %>
          <% end %>
    </div>
</div>

</div>